// AUTO-GENERATED BY scripts/generate-contract-models.mjs. DO NOT EDIT.

/**
 * @typedef {Object} AuthErrorResponse
 * @property {string|null} code
 * @property {string|null} message
 * @property {boolean|null} captchaRequired
 * @property {number|null} remainingAttempts
 */

export const AUTH_ERROR_RESPONSE_FIELDS = Object.freeze([
  'code',
  'message',
  'captchaRequired',
  'remainingAttempts',
]);

/**
 * @param {Partial<AuthErrorResponse>} [overrides={}]
 * @returns {AuthErrorResponse}
 */
export function createAuthErrorResponse(overrides = {}) {
  return {
    code: null,
    message: null,
    captchaRequired: null,
    remainingAttempts: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} AuthRequest
 * @property {string|null} username
 * @property {string|null} email
 * @property {string|null} password
 * @property {string|null} phone
 */

export const AUTH_REQUEST_FIELDS = Object.freeze([
  'username',
  'email',
  'password',
  'phone',
]);

/**
 * @param {Partial<AuthRequest>} [overrides={}]
 * @returns {AuthRequest}
 */
export function createAuthRequest(overrides = {}) {
  return {
    username: null,
    email: null,
    password: null,
    phone: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} AuthResponse
 * @property {string|null} token
 * @property {string|null} type
 * @property {number|null} id
 * @property {string|null} username
 * @property {string|null} displayName
 * @property {string|null} email
 * @property {string|null} phone
 * @property {string|null} avatarUrl
 */

export const AUTH_RESPONSE_FIELDS = Object.freeze([
  'token',
  'type',
  'id',
  'username',
  'displayName',
  'email',
  'phone',
  'avatarUrl',
]);

/**
 * @param {Partial<AuthResponse>} [overrides={}]
 * @returns {AuthResponse}
 */
export function createAuthResponse(overrides = {}) {
  return {
    token: null,
    type: null,
    id: null,
    username: null,
    displayName: null,
    email: null,
    phone: null,
    avatarUrl: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} CaptchaResponse
 * @property {string|null} captchaId
 * @property {string|null} imageBase64
 * @property {number|null} expiresInSeconds
 */

export const CAPTCHA_RESPONSE_FIELDS = Object.freeze([
  'captchaId',
  'imageBase64',
  'expiresInSeconds',
]);

/**
 * @param {Partial<CaptchaResponse>} [overrides={}]
 * @returns {CaptchaResponse}
 */
export function createCaptchaResponse(overrides = {}) {
  return {
    captchaId: null,
    imageBase64: null,
    expiresInSeconds: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} ForgotPasswordRequest
 * @property {string|null} email
 */

export const FORGOT_PASSWORD_REQUEST_FIELDS = Object.freeze([
  'email',
]);

/**
 * @param {Partial<ForgotPasswordRequest>} [overrides={}]
 * @returns {ForgotPasswordRequest}
 */
export function createForgotPasswordRequest(overrides = {}) {
  return {
    email: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} LoginRequest
 * @property {string|null} username
 * @property {string|null} password
 * @property {string|null} captchaId
 * @property {string|null} captchaCode
 */

export const LOGIN_REQUEST_FIELDS = Object.freeze([
  'username',
  'password',
  'captchaId',
  'captchaCode',
]);

/**
 * @param {Partial<LoginRequest>} [overrides={}]
 * @returns {LoginRequest}
 */
export function createLoginRequest(overrides = {}) {
  return {
    username: null,
    password: null,
    captchaId: null,
    captchaCode: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} ResetPasswordRequest
 * @property {string|null} email
 * @property {string|null} code
 * @property {string|null} newPassword
 */

export const RESET_PASSWORD_REQUEST_FIELDS = Object.freeze([
  'email',
  'code',
  'newPassword',
]);

/**
 * @param {Partial<ResetPasswordRequest>} [overrides={}]
 * @returns {ResetPasswordRequest}
 */
export function createResetPasswordRequest(overrides = {}) {
  return {
    email: null,
    code: null,
    newPassword: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} SmsCodeRequest
 * @property {string|null} phone
 */

export const SMS_CODE_REQUEST_FIELDS = Object.freeze([
  'phone',
]);

/**
 * @param {Partial<SmsCodeRequest>} [overrides={}]
 * @returns {SmsCodeRequest}
 */
export function createSmsCodeRequest(overrides = {}) {
  return {
    phone: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} SmsLoginRequest
 * @property {string|null} phone
 * @property {string|null} code
 */

export const SMS_LOGIN_REQUEST_FIELDS = Object.freeze([
  'phone',
  'code',
]);

/**
 * @param {Partial<SmsLoginRequest>} [overrides={}]
 * @returns {SmsLoginRequest}
 */
export function createSmsLoginRequest(overrides = {}) {
  return {
    phone: null,
    code: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} UserDTO
 * @property {number|null} id
 * @property {string|null} username
 * @property {string|null} displayName
 * @property {string|null} email
 * @property {string|null} phone
 * @property {string|null} avatarUrl
 * @property {string|null} bio
 * @property {string|null} gender
 * @property {string|null} birthday
 * @property {string|null} region
 * @property {string|null} createdAt
 * @property {string|null} updatedAt
 */

export const USER_DTO_FIELDS = Object.freeze([
  'id',
  'username',
  'displayName',
  'email',
  'phone',
  'avatarUrl',
  'bio',
  'gender',
  'birthday',
  'region',
  'createdAt',
  'updatedAt',
]);

/**
 * @param {Partial<UserDTO>} [overrides={}]
 * @returns {UserDTO}
 */
export function createUserDTO(overrides = {}) {
  return {
    id: null,
    username: null,
    displayName: null,
    email: null,
    phone: null,
    avatarUrl: null,
    bio: null,
    gender: null,
    birthday: null,
    region: null,
    createdAt: null,
    updatedAt: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} CommentDTO
 * @property {number|null} id
 * @property {string|null} content
 * @property {number|null} userId
 * @property {string|null} username
 * @property {string|null} userAvatarUrl
 * @property {number|null} postId
 * @property {string|null} createdAt
 * @property {string|null} updatedAt
 * @property {number|null} likeCount
 */

export const COMMENT_DTO_FIELDS = Object.freeze([
  'id',
  'content',
  'userId',
  'username',
  'userAvatarUrl',
  'postId',
  'createdAt',
  'updatedAt',
  'likeCount',
]);

/**
 * @param {Partial<CommentDTO>} [overrides={}]
 * @returns {CommentDTO}
 */
export function createCommentDTO(overrides = {}) {
  return {
    id: null,
    content: null,
    userId: null,
    username: null,
    userAvatarUrl: null,
    postId: null,
    createdAt: null,
    updatedAt: null,
    likeCount: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} PostCollectionResponse
 * @property {Array<PostDTO>} items
 * @property {PaginationMeta|null} pagination
 * @property {RetrievalMeta|null} retrieval
 */

export const POST_COLLECTION_RESPONSE_FIELDS = Object.freeze([
  'items',
  'pagination',
  'retrieval',
]);

/**
 * @param {Partial<PostCollectionResponse>} [overrides={}]
 * @returns {PostCollectionResponse}
 */
export function createPostCollectionResponse(overrides = {}) {
  return {
    items: [],
    pagination: null,
    retrieval: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} PostDTO
 * @property {number|null} id
 * @property {string|null} content
 * @property {Array<string>} imageUrls
 * @property {number|null} userId
 * @property {string|null} username
 * @property {string|null} userAvatarUrl
 * @property {string|null} locationName
 * @property {string|null} locationAddress
 * @property {number|null} latitude
 * @property {number|null} longitude
 * @property {string|null} gisPoint
 * @property {string|null} createdAt
 * @property {string|null} updatedAt
 * @property {number|null} likeCount
 * @property {number|null} commentCount
 */

export const POST_DTO_FIELDS = Object.freeze([
  'id',
  'content',
  'imageUrls',
  'userId',
  'username',
  'userAvatarUrl',
  'locationName',
  'locationAddress',
  'latitude',
  'longitude',
  'gisPoint',
  'createdAt',
  'updatedAt',
  'likeCount',
  'commentCount',
]);

/**
 * @param {Partial<PostDTO>} [overrides={}]
 * @returns {PostDTO}
 */
export function createPostDTO(overrides = {}) {
  return {
    id: null,
    content: null,
    imageUrls: [],
    userId: null,
    username: null,
    userAvatarUrl: null,
    locationName: null,
    locationAddress: null,
    latitude: null,
    longitude: null,
    gisPoint: null,
    createdAt: null,
    updatedAt: null,
    likeCount: null,
    commentCount: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} LocationSuggestionDTO
 * @property {string|null} name
 * @property {string|null} address
 * @property {number|null} latitude
 * @property {number|null} longitude
 * @property {string|null} district
 * @property {string|null} city
 */

export const LOCATION_SUGGESTION_DTO_FIELDS = Object.freeze([
  'name',
  'address',
  'latitude',
  'longitude',
  'district',
  'city',
]);

/**
 * @param {Partial<LocationSuggestionDTO>} [overrides={}]
 * @returns {LocationSuggestionDTO}
 */
export function createLocationSuggestionDTO(overrides = {}) {
  return {
    name: null,
    address: null,
    latitude: null,
    longitude: null,
    district: null,
    city: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} MealCatalogItemDTO
 * @property {number|null} id
 * @property {string|null} code
 * @property {string|null} slug
 * @property {string|null} name
 * @property {string|null} category
 * @property {string|null} subcategory
 * @property {string|null} cookingMethod
 * @property {string|null} rawFlavorText
 * @property {Array<string>} flavorTags
 * @property {Array<string>} featureTags
 * @property {Array<string>} ingredientTags
 * @property {number|null} sourceIndex
 */

export const MEAL_CATALOG_ITEM_DTO_FIELDS = Object.freeze([
  'id',
  'code',
  'slug',
  'name',
  'category',
  'subcategory',
  'cookingMethod',
  'rawFlavorText',
  'flavorTags',
  'featureTags',
  'ingredientTags',
  'sourceIndex',
]);

/**
 * @param {Partial<MealCatalogItemDTO>} [overrides={}]
 * @returns {MealCatalogItemDTO}
 */
export function createMealCatalogItemDTO(overrides = {}) {
  return {
    id: null,
    code: null,
    slug: null,
    name: null,
    category: null,
    subcategory: null,
    cookingMethod: null,
    rawFlavorText: null,
    flavorTags: [],
    featureTags: [],
    ingredientTags: [],
    sourceIndex: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} MealCatalogResponseDTO
 * @property {string|null} datasetVersion
 * @property {number|null} total
 * @property {Array<MealCatalogItemDTO>} items
 */

export const MEAL_CATALOG_RESPONSE_DTO_FIELDS = Object.freeze([
  'datasetVersion',
  'total',
  'items',
]);

/**
 * @param {Partial<MealCatalogResponseDTO>} [overrides={}]
 * @returns {MealCatalogResponseDTO}
 */
export function createMealCatalogResponseDTO(overrides = {}) {
  return {
    datasetVersion: null,
    total: null,
    items: [],
    ...overrides,
  };
}

/**
 * @typedef {Object} MealRecipeCollectionResponseDTO
 * @property {Array<RecipeDTO>} items
 * @property {PaginationMeta|null} pagination
 * @property {RetrievalMeta|null} retrieval
 */

export const MEAL_RECIPE_COLLECTION_RESPONSE_DTO_FIELDS = Object.freeze([
  'items',
  'pagination',
  'retrieval',
]);

/**
 * @param {Partial<MealRecipeCollectionResponseDTO>} [overrides={}]
 * @returns {MealRecipeCollectionResponseDTO}
 */
export function createMealRecipeCollectionResponseDTO(overrides = {}) {
  return {
    items: [],
    pagination: null,
    retrieval: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} MealRecommendationFormDTO
 * @property {string|null} sourceMode
 * @property {number|null} catalogItemId
 * @property {number|null} dishCount
 * @property {number|null} totalCalories
 * @property {string|null} staple
 * @property {string|null} locale
 */

export const MEAL_RECOMMENDATION_FORM_DTO_FIELDS = Object.freeze([
  'sourceMode',
  'catalogItemId',
  'dishCount',
  'totalCalories',
  'staple',
  'locale',
]);

/**
 * @param {Partial<MealRecommendationFormDTO>} [overrides={}]
 * @returns {MealRecommendationFormDTO}
 */
export function createMealRecommendationFormDTO(overrides = {}) {
  return {
    sourceMode: null,
    catalogItemId: null,
    dishCount: null,
    totalCalories: null,
    staple: null,
    locale: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} MealRecommendationRequestDTO
 * @property {string|null} sourceText
 * @property {string|null} sourceMode
 * @property {number|null} catalogItemId
 * @property {number|null} dishCount
 * @property {number|null} totalCalories
 * @property {string|null} staple
 * @property {string|null} locale
 * @property {Array<string>} recentDishTitles
 */

export const MEAL_RECOMMENDATION_REQUEST_DTO_FIELDS = Object.freeze([
  'sourceText',
  'sourceMode',
  'catalogItemId',
  'dishCount',
  'totalCalories',
  'staple',
  'locale',
  'recentDishTitles',
]);

/**
 * @param {Partial<MealRecommendationRequestDTO>} [overrides={}]
 * @returns {MealRecommendationRequestDTO}
 */
export function createMealRecommendationRequestDTO(overrides = {}) {
  return {
    sourceText: null,
    sourceMode: null,
    catalogItemId: null,
    dishCount: null,
    totalCalories: null,
    staple: null,
    locale: null,
    recentDishTitles: [],
    ...overrides,
  };
}

/**
 * @typedef {Object} MealRecommendationResponseDTO
 * @property {string|null} requestId
 * @property {string|null} sourceText
 * @property {MealRecommendationFormDTO|null} form
 * @property {string|null} provider
 * @property {Array<RecipeDTO>} items
 * @property {boolean|null} emptyState
 */

export const MEAL_RECOMMENDATION_RESPONSE_DTO_FIELDS = Object.freeze([
  'requestId',
  'sourceText',
  'form',
  'provider',
  'items',
  'emptyState',
]);

/**
 * @param {Partial<MealRecommendationResponseDTO>} [overrides={}]
 * @returns {MealRecommendationResponseDTO}
 */
export function createMealRecommendationResponseDTO(overrides = {}) {
  return {
    requestId: null,
    sourceText: null,
    form: null,
    provider: null,
    items: [],
    emptyState: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} RecipeDTO
 * @property {number|null} id
 * @property {number|null} catalogItemId
 * @property {string|null} title
 * @property {string|null} summary
 * @property {number|null} estimatedCalories
 * @property {Array<RecipeIngredientDTO>} ingredients
 * @property {Array<RecipeIngredientDTO>} seasonings
 * @property {Array<RecipeStepDTO>} steps
 * @property {string|null} imageUrl
 * @property {string|null} imageStatus
 * @property {string|null} stepsStatus
 * @property {string|null} preference
 */

export const RECIPE_DTO_FIELDS = Object.freeze([
  'id',
  'catalogItemId',
  'title',
  'summary',
  'estimatedCalories',
  'ingredients',
  'seasonings',
  'steps',
  'imageUrl',
  'imageStatus',
  'stepsStatus',
  'preference',
]);

/**
 * @param {Partial<RecipeDTO>} [overrides={}]
 * @returns {RecipeDTO}
 */
export function createRecipeDTO(overrides = {}) {
  return {
    id: null,
    catalogItemId: null,
    title: null,
    summary: null,
    estimatedCalories: null,
    ingredients: [],
    seasonings: [],
    steps: [],
    imageUrl: null,
    imageStatus: null,
    stepsStatus: null,
    preference: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} RecipeImageResponseDTO
 * @property {number|null} recipeId
 * @property {string|null} imageUrl
 * @property {string|null} imageStatus
 */

export const RECIPE_IMAGE_RESPONSE_DTO_FIELDS = Object.freeze([
  'recipeId',
  'imageUrl',
  'imageStatus',
]);

/**
 * @param {Partial<RecipeImageResponseDTO>} [overrides={}]
 * @returns {RecipeImageResponseDTO}
 */
export function createRecipeImageResponseDTO(overrides = {}) {
  return {
    recipeId: null,
    imageUrl: null,
    imageStatus: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} RecipeIngredientDTO
 * @property {string|null} name
 * @property {string|null} amount
 */

export const RECIPE_INGREDIENT_DTO_FIELDS = Object.freeze([
  'name',
  'amount',
]);

/**
 * @param {Partial<RecipeIngredientDTO>} [overrides={}]
 * @returns {RecipeIngredientDTO}
 */
export function createRecipeIngredientDTO(overrides = {}) {
  return {
    name: null,
    amount: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} RecipePreferenceRequestDTO
 * @property {string|null} preference
 */

export const RECIPE_PREFERENCE_REQUEST_DTO_FIELDS = Object.freeze([
  'preference',
]);

/**
 * @param {Partial<RecipePreferenceRequestDTO>} [overrides={}]
 * @returns {RecipePreferenceRequestDTO}
 */
export function createRecipePreferenceRequestDTO(overrides = {}) {
  return {
    preference: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} RecipePreferenceResponseDTO
 * @property {number|null} recipeId
 * @property {string|null} preference
 * @property {string|null} updatedAt
 */

export const RECIPE_PREFERENCE_RESPONSE_DTO_FIELDS = Object.freeze([
  'recipeId',
  'preference',
  'updatedAt',
]);

/**
 * @param {Partial<RecipePreferenceResponseDTO>} [overrides={}]
 * @returns {RecipePreferenceResponseDTO}
 */
export function createRecipePreferenceResponseDTO(overrides = {}) {
  return {
    recipeId: null,
    preference: null,
    updatedAt: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} RecipeStepDTO
 * @property {number|null} index
 * @property {string|null} content
 */

export const RECIPE_STEP_DTO_FIELDS = Object.freeze([
  'index',
  'content',
]);

/**
 * @param {Partial<RecipeStepDTO>} [overrides={}]
 * @returns {RecipeStepDTO}
 */
export function createRecipeStepDTO(overrides = {}) {
  return {
    index: null,
    content: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} VoiceTranscriptionResponseDTO
 * @property {string|null} text
 * @property {string|null} provider
 * @property {number|null} durationMs
 * @property {boolean|null} emptyResult
 */

export const VOICE_TRANSCRIPTION_RESPONSE_DTO_FIELDS = Object.freeze([
  'text',
  'provider',
  'durationMs',
  'emptyResult',
]);

/**
 * @param {Partial<VoiceTranscriptionResponseDTO>} [overrides={}]
 * @returns {VoiceTranscriptionResponseDTO}
 */
export function createVoiceTranscriptionResponseDTO(overrides = {}) {
  return {
    text: null,
    provider: null,
    durationMs: null,
    emptyResult: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} FileUploadResponse
 * @property {string|null} fileName
 * @property {string|null} fileUrl
 * @property {string|null} fileType
 * @property {number|null} size
 */

export const FILE_UPLOAD_RESPONSE_FIELDS = Object.freeze([
  'fileName',
  'fileUrl',
  'fileType',
  'size',
]);

/**
 * @param {Partial<FileUploadResponse>} [overrides={}]
 * @returns {FileUploadResponse}
 */
export function createFileUploadResponse(overrides = {}) {
  return {
    fileName: null,
    fileUrl: null,
    fileType: null,
    size: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} MessageResponse
 * @property {string|null} message
 * @property {string|null} service
 * @property {string|null} provider
 * @property {boolean|null} setupRequired
 */

export const MESSAGE_RESPONSE_FIELDS = Object.freeze([
  'message',
  'service',
  'provider',
  'setupRequired',
]);

/**
 * @param {Partial<MessageResponse>} [overrides={}]
 * @returns {MessageResponse}
 */
export function createMessageResponse(overrides = {}) {
  return {
    message: null,
    service: null,
    provider: null,
    setupRequired: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} PaginationMeta
 * @property {number|null} page
 * @property {number|null} size
 * @property {number|null} totalItems
 * @property {number|null} totalPages
 * @property {boolean|null} hasNext
 * @property {boolean|null} hasPrevious
 */

export const PAGINATION_META_FIELDS = Object.freeze([
  'page',
  'size',
  'totalItems',
  'totalPages',
  'hasNext',
  'hasPrevious',
]);

/**
 * @param {Partial<PaginationMeta>} [overrides={}]
 * @returns {PaginationMeta}
 */
export function createPaginationMeta(overrides = {}) {
  return {
    page: null,
    size: null,
    totalItems: null,
    totalPages: null,
    hasNext: null,
    hasPrevious: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} RetrievalMeta
 * @property {string|null} scene
 * @property {string|null} keyword
 * @property {string|null} sortStrategy
 * @property {string|null} provider
 */

export const RETRIEVAL_META_FIELDS = Object.freeze([
  'scene',
  'keyword',
  'sortStrategy',
  'provider',
]);

/**
 * @param {Partial<RetrievalMeta>} [overrides={}]
 * @returns {RetrievalMeta}
 */
export function createRetrievalMeta(overrides = {}) {
  return {
    scene: null,
    keyword: null,
    sortStrategy: null,
    provider: null,
    ...overrides,
  };
}

export const CONTRACT_MODEL_NAMES = Object.freeze([
  'AuthErrorResponse',
  'AuthRequest',
  'AuthResponse',
  'CaptchaResponse',
  'ForgotPasswordRequest',
  'LoginRequest',
  'ResetPasswordRequest',
  'SmsCodeRequest',
  'SmsLoginRequest',
  'UserDTO',
  'CommentDTO',
  'PostCollectionResponse',
  'PostDTO',
  'LocationSuggestionDTO',
  'MealCatalogItemDTO',
  'MealCatalogResponseDTO',
  'MealRecipeCollectionResponseDTO',
  'MealRecommendationFormDTO',
  'MealRecommendationRequestDTO',
  'MealRecommendationResponseDTO',
  'RecipeDTO',
  'RecipeImageResponseDTO',
  'RecipeIngredientDTO',
  'RecipePreferenceRequestDTO',
  'RecipePreferenceResponseDTO',
  'RecipeStepDTO',
  'VoiceTranscriptionResponseDTO',
  'FileUploadResponse',
  'MessageResponse',
  'PaginationMeta',
  'RetrievalMeta',
]);

export const CONTRACT_MODEL_FACTORIES = Object.freeze({
  AuthErrorResponse: createAuthErrorResponse,
  AuthRequest: createAuthRequest,
  AuthResponse: createAuthResponse,
  CaptchaResponse: createCaptchaResponse,
  ForgotPasswordRequest: createForgotPasswordRequest,
  LoginRequest: createLoginRequest,
  ResetPasswordRequest: createResetPasswordRequest,
  SmsCodeRequest: createSmsCodeRequest,
  SmsLoginRequest: createSmsLoginRequest,
  UserDTO: createUserDTO,
  CommentDTO: createCommentDTO,
  PostCollectionResponse: createPostCollectionResponse,
  PostDTO: createPostDTO,
  LocationSuggestionDTO: createLocationSuggestionDTO,
  MealCatalogItemDTO: createMealCatalogItemDTO,
  MealCatalogResponseDTO: createMealCatalogResponseDTO,
  MealRecipeCollectionResponseDTO: createMealRecipeCollectionResponseDTO,
  MealRecommendationFormDTO: createMealRecommendationFormDTO,
  MealRecommendationRequestDTO: createMealRecommendationRequestDTO,
  MealRecommendationResponseDTO: createMealRecommendationResponseDTO,
  RecipeDTO: createRecipeDTO,
  RecipeImageResponseDTO: createRecipeImageResponseDTO,
  RecipeIngredientDTO: createRecipeIngredientDTO,
  RecipePreferenceRequestDTO: createRecipePreferenceRequestDTO,
  RecipePreferenceResponseDTO: createRecipePreferenceResponseDTO,
  RecipeStepDTO: createRecipeStepDTO,
  VoiceTranscriptionResponseDTO: createVoiceTranscriptionResponseDTO,
  FileUploadResponse: createFileUploadResponse,
  MessageResponse: createMessageResponse,
  PaginationMeta: createPaginationMeta,
  RetrievalMeta: createRetrievalMeta,
});

