server.address=0.0.0.0

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.docs.enabled=true
app.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000

logging.level.com.quickstart.template=DEBUG
logging.level.org.springframework.security=DEBUG
